# Generated by Django 5.1 on 2024-08-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='resue',
            new_name='resume',
        ),
    ]
